# Generated by Django 4.1.2 on 2023-04-23 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('open', models.BooleanField()),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_points', models.PositiveSmallIntegerField()),
                ('max_points', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'criteria',
                'ordering': ['-max_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.competition')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['competition', 'label'],
                'unique_together': {('competition', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competition', 'judge'],
                'unique_together': {('competition', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.criterion')),
                ('judgement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.judgement')),
            ],
            options={
                'ordering': ['judgement', 'criterion'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='criteria',
            field=models.ManyToManyField(to='brews.criterion'),
        ),
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.entry')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.ranking')),
            ],
            options={
                'ordering': ['ranking', 'ordinal', 'entry'],
                'unique_together': {('ranking', 'ordinal')},
            },
        ),
    ]
