# Generated by Django 4.2 on 2023-04-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0002_remove_competition_judges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='open',
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('REGR', 'Registration'), ('OPEN', 'Open'), ('CLSD', 'Closed'), ('COMP', 'Complete')], default='REGR', max_length=4),
        ),
    ]
