# Generated by Django 4.2 on 2023-04-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0004_alter_entry_label_heat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heat',
            options={'ordering': ['round', 'label']},
        ),
        migrations.RemoveField(
            model_name='heat',
            name='competition',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.competition')),
            ],
            options={
                'ordering': ['competition', 'number'],
            },
        ),
        migrations.AlterField(
            model_name='heat',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brews.round'),
        ),
    ]
