# Generated by Django 4.2 on 2023-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0005_alter_heat_options_remove_heat_competition_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat',
            name='status',
            field=models.CharField(choices=[('REGR', 'Registration'), ('OPEN', 'Open'), ('CLSD', 'Closed'), ('COMP', 'Complete')], default='REGR', max_length=4),
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('REGR', 'Registration'), ('OPEN', 'Open'), ('CLSD', 'Closed'), ('COMP', 'Complete')], default='REGR', max_length=4),
        ),
    ]
