# Generated by Django 4.2 on 2023-04-30 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brews', '0006_heat_status_round_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgement',
            options={'ordering': ['heat', 'judge']},
        ),
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='heat',
            name='entries',
            field=models.ManyToManyField(to='brews.entry'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='heat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brews.heat'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together={('heat', 'judge')},
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='competition',
        ),
    ]
