# Generated by Django 4.2 on 2023-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0008_round_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='winners',
        ),
        migrations.AddField(
            model_name='heat',
            name='winners',
            field=models.ManyToManyField(related_name='heats_won', to='brews.entry'),
        ),
        migrations.AlterField(
            model_name='heat',
            name='entries',
            field=models.ManyToManyField(related_name='heats_entered', to='brews.entry'),
        ),
    ]
