# Generated by Django 4.2 on 2023-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0010_round_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='heats_won', to='brews.entry'),
        ),
    ]
