# Generated by Django 4.2 on 2023-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0011_alter_heat_winners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heat',
            options={'ordering': ['round', 'number']},
        ),
        migrations.RemoveField(
            model_name='heat',
            name='label',
        ),
        migrations.AddField(
            model_name='heat',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
