# Generated by Django 4.2 on 2023-05-01 21:02

import brews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0013_heat_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='labels',
            field=models.CharField(default=brews.models.get_random_labels, max_length=26),
        ),
    ]
