# Generated by Django 4.2 on 2023-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0014_competition_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='heats_entered', to='brews.entry'),
        ),
    ]
