# Generated by Django 4.2 on 2023-05-02 18:04

import brews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0015_alter_heat_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='access_key',
            field=models.CharField(default=brews.models.get_random_access_key, max_length=10),
        ),
    ]
