# Generated by Django 4.2 on 2023-05-03 13:59

import brews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0016_competition_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='access_key',
            field=models.CharField(blank=True, default=brews.models.get_random_access_key, max_length=10, null=True),
        ),
    ]
